# Generated by Django 5.2.5 on 2026-04-09 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appuser_claim_amount_appuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAnalysis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('claim_id', models.CharField(db_index=True, max_length=100)),
                ('fraud_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='low', max_length=50)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('full_report_json', models.TextField(blank=True, null=True)),
                ('inconsistency_score', models.IntegerField(default=0)),
                ('deepfake_score', models.IntegerField(default=0)),
                ('pattern_score', models.IntegerField(default=0)),
                ('metadata_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fraud_analysis_reports',
            },
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='risk',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=50),
        ),
    ]
